version: '2'
services:
  myerp.db:
    image: postgres:10
    ports:
       - "5432:5432"
    volumes:
#   #      - "./data/db:/var/lib/postgresql/data"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=alegia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Yocorps17
      
