language: 
  - node_js
  - java
node_js:
  - "8.2.1"
jdk:
  - openjdk8

install :
  - npm install newman

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before script:
  - node --version
  - npm --version
  - cd ../../
  

script:
  - cd Microservice/eureka
  - mvn clean
  - mvn install
  - mvn test
  - cd ..
  - cd microservice-adresse
  - mvn clean
  - mvn install 
  - cd ..
  - cd test
  - java -jar eureka/target/eureka-0.0.1-SNAPSHOT.jar & java -jar microservice-adresse/target/microservice-adresse-0.0.1-SNAPSHOT.jar & newman run Alegia.postman_collection.json



