language: 
  - node_js
  - java
node_js:
  - "8.2.1"
jdk:
  - openjdk8

install :
  - npm install newman

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before script:
  - node --version
  - npm --version
  - cd ../../
  

script:
  - cd Microservice/eureka
  - mvn clean
  - mvn package
  - mvn install
  - start "Eureka" java -jar target/eureka-0.0.1-SNAPSHOT.jar
  - mvn test
  - cd ..
  - cd microservice-adresse
  - mvn clean
  - mvn package
  - mvn install
  - start "Microservice-Adresse" java -jar target/microservice-adresse-0.0.1-SNAPSHOT.jar
  - cd ../../
  - cd test
  - newman run Alegia.postman_collection.json


